// let wrap = document.getElementsByTagName("div").item("wrap");
// wrap.style.margin = "0 auto";
// wrap.style.width = "1200px";
//
// let formGroup = document.getElementsByTagName("div").item("formGroup");
// formGroup.style.width = "500px";
// formGroup.style.margin = "0 auto";
// formGroup.style.boxShadow = " 0 0 10px rgba(80,80,80,0.5)";
// formGroup.style.padding = "1.2rem 1.5rem";
// formGroup.style.boxSizing = "borderBox"
//
// let label = document.getElementsByTagName("label").item("label");
// label.style.width = "35%";
// label.style.padding = " 0.5rem 1.5rem";
// label.style.boxSizing = "borderBox";
// label.style.display = "inlineBlock";
// label.style.marginBottom = "10px";
// label.style.textAlign = "right";
//
// let input = document.getElementsByTagName("input").item("input");
// input.style.width = "60%";
// input.style.padding = "0.5rem 1.5rem";
// input.style.display = "inlineBlock";
// input.style.boxSizing = "borderBox";
// input.style.border = "1px solid #cccccc";
// input.style.borderRadius = "4px";
// input.style.marginBottom = "10px";

let bywrap = document.getElementsByTagName("div").namedItem("wrap");
bywrap.style.margin = "0 auto";
bywrap.style.width = "1200px";

let byfromGroup = document.getElementsByTagName("div").namedItem("fromGroup");
byfromGroup.style.width = "500px";
byfromGroup.style.margin = "0 auto";
byfromGroup.style.boxShadow = " 0 0 10px rgba(80,80,80,0.5)";
byfromGroup.style.padding = "1.2rem 1.5rem";
byfromGroup.style.boxSizing = "borderBox";


let byinput = document.getElementsByTagName("input").namedItem("a1")
byinput.style.width = "60%";
byinput.style.padding = "0.5rem 1.5rem";
byinput.style.display = "inlineBlock";
byinput.style.boxSizing = "borderBox";
byinput.style.border = "1px solid #cccccc";
byinput.style.borderRadius = "4px";
byinput.style.marginBottom = "10px";

let byinput2 = document.getElementsByTagName("input").namedItem("a2")
byinput2.style.width = "60%";
byinput2.style.padding = "0.5rem 1.5rem";
byinput2.style.display = "inlineBlock";
byinput2.style.boxSizing = "borderBox";
byinput2.style.border = "1px solid #cccccc";
byinput2.style.borderRadius = "4px";
byinput2.style.marginBottom = "10px";

let byinput3 = document.getElementsByTagName("input").namedItem("a3")
byinput3.style.width = "60%";
byinput3.style.padding = "0.5rem 1.5rem";
byinput3.style.display = "inlineBlock";
byinput3.style.boxSizing = "borderBox";
byinput3.style.border = "1px solid #cccccc";
byinput3.style.borderRadius = "4px";
byinput3.style.marginBottom = "10px";

let byinput4 = document.getElementsByTagName("input").namedItem("a4")
byinput4.style.width = "60%";
byinput4.style.padding = "0.5rem 1.5rem";
byinput4.style.display = "inlineBlock";
byinput4.style.boxSizing = "borderBox";
byinput4.style.border = "1px solid #cccccc";
byinput4.style.borderRadius = "4px";
byinput4.style.marginBottom = "10px";

let byinput5 = document.getElementsByTagName("input").namedItem("a5")
byinput5.style.width = "60%";
byinput5.style.padding = "0.5rem 1.5rem";
byinput5.style.display = "inlineBlock";
byinput5.style.boxSizing = "borderBox";
byinput5.style.border = "1px solid #cccccc";
byinput5.style.borderRadius = "4px";
byinput5.style.marginBottom = "10px";

let byinput6 = document.getElementsByTagName("input").namedItem("a6")
byinput6.style.width = "60%";
byinput6.style.padding = "0.5rem 1.5rem";
byinput6.style.display = "inlineBlock";
byinput6.style.boxSizing = "borderBox";
byinput6.style.border = "1px solid #cccccc";
byinput6.style.borderRadius = "4px";
byinput6.style.marginBottom = "10px";

let byinput7 = document.getElementsByTagName("input").namedItem("a7")
byinput7.style.width = "60%";
byinput7.style.padding = "0.5rem 1.5rem";
byinput7.style.display = "inlineBlock";
byinput7.style.boxSizing = "borderBox";
byinput7.style.border = "1px solid #cccccc";
byinput7.style.borderRadius = "4px";
byinput7.style.marginBottom = "10px";

let byinput8 = document.getElementsByTagName("input").namedItem("a8")
byinput8.style.width = "60%";
byinput8.style.padding = "0.5rem 1.5rem";
byinput8.style.display = "inlineBlock";
byinput8.style.boxSizing = "borderBox";
byinput8.style.border = "1px solid #cccccc";
byinput8.style.borderRadius = "4px";
byinput8.style.marginBottom = "10px";


let byinput9 = document.getElementsByTagName("input").namedItem("a9")
byinput9.style.width = "60%";
byinput9.style.padding = "0.5rem 1.5rem";
byinput9.style.display = "inlineBlock";
byinput9.style.boxSizing = "borderBox";
byinput9.style.border = "1px solid #cccccc";
byinput9.style.borderRadius = "4px";
byinput9.style.marginBottom = "10px";


let byinput10 = document.getElementsByTagName("input").namedItem("a10")
byinput10.style.width = "60%";
byinput10.style.padding = "0.5rem 1.5rem";
byinput10.style.display = "inlineBlock";
byinput10.style.boxSizing = "borderBox";
byinput10.style.border = "1px solid #cccccc";
byinput10.style.borderRadius = "4px";
byinput10.style.marginBottom = "10px";


let bylabel = document.getElementsByTagName("label").namedItem("l1");
bylabel.style.width = "35%";
bylabel.style.padding = "0.5rem 1.5rem";
bylabel.style.boxSizing = "borderBox";
bylabel.style.display = "inlineBlock";
bylabel.style.marginBottom = "10px";
bylabel.style.textAlign = "right";

let bylabel1 = document.getElementsByTagName("label").namedItem("l2");
bylabel1.style.width = "35%";
bylabel1.style.padding = "0.5rem 1.5rem";
bylabel1.style.boxSizing = "borderBox";
bylabel1.style.display = "inlineBlock";
bylabel1.style.marginBottom = "10px";
bylabel1.style.textAlign = "right";
let bylabel3 = document.getElementsByTagName("label").namedItem("l3");
bylabel3.style.width = "35%";
bylabel3.style.padding = "0.5rem 1.5rem";
bylabel3.style.boxSizing = "borderBox";
bylabel3.style.display = "inlineBlock";
bylabel3.style.marginBottom = "10px";
bylabel3.style.textAlign = "right";
let bylabel4 = document.getElementsByTagName("label").namedItem("l4");
bylabel4.style.width = "35%"
bylabel4.style.padding = "0.5rem 1.5rem";
bylabel4.style.boxSizing = "borderBox";
bylabel4.style.display = "inlineBlock";
bylabel4.style.marginBottom = "10px";
bylabel4.style.textAlign = "right";
let bylabel5 = document.getElementsByTagName("label").namedItem("l5");
bylabel5.style.width = "35%";
bylabel5.style.padding = "0.5rem 1.5rem";
bylabel5.style.boxSizing = "borderBox";
bylabel5.style.display = "inlineBlock";
bylabel5.style.marginBottom = "10px";
bylabel5.style.textAlign = "right";
let bylabel6 = document.getElementsByTagName("label").namedItem("l6");
bylabel6.style.width = "35%";
bylabel6.style.padding = "0.5rem 1.5rem";
bylabel6.style.boxSizing = "borderBox";
bylabel6.style.display = "inlineBlock";
bylabel6.style.marginBottom = "10px";
bylabel6.style.textAlign = "right";
let bylabel7 = document.getElementsByTagName("label").namedItem("l7");
bylabel7.style.width = "35%";
bylabel7.style.padding = "0.5rem 1.5rem";
bylabel7.style.boxSizing = "borderBox";
bylabel7.style.display = "inlineBlock";
bylabel7.style.marginBottom = "10px";
bylabel7.style.textAlign = "right";
let bylabel8 = document.getElementsByTagName("label").namedItem("l8");
bylabel8.style.width = "35%";
bylabel8.style.padding = "0.5rem 1.5rem";
bylabel8.style.boxSizing = "borderBox";
bylabel8.style.display = "inlineBlock";
bylabel8.style.marginBottom = "10px";
bylabel8.style.textAlign = "right";
let bylabel9 = document.getElementsByTagName("label").namedItem("l9");
bylabel9.style.width = "35%";
bylabel9.style.padding = "0.5rem 1.5rem";
bylabel9.style.boxSizing = "borderBox";
bylabel9.style.display = "inlineBlock";
bylabel9.style.marginBottom = "10px";
bylabel9.style.textAlign = "right";
let bylabel10 = document.getElementsByTagName("label").namedItem("l10");
bylabel10.style.width = "35%";
bylabel10.style.padding = "0.5rem 1.5rem";
bylabel10.style.boxSizing = "borderBox";
bylabel10.style.display = "inlineBlock";
bylabel10.style.marginBottom = "10px";
bylabel10.style.textAlign = "right";
let bylabel11 = document.getElementsByTagName("label").namedItem("l11");
bylabel11.style.width = "35%";
bylabel11.style.padding = "0.5rem 1.5rem";
bylabel11.style.boxSizing = "borderBox";
bylabel11.style.display = "inlineBlock";
bylabel11.style.marginBottom = "10px";
bylabel11.style.textAlign = "right";
let bylabel12 = document.getElementsByTagName("label").namedItem("l12");
bylabel12.style.width = "35%";
bylabel12.style.padding = "0.5rem 1.5rem";
bylabel12.style.boxSizing = "borderBox";
bylabel12.style.display = "inlineBlock";
bylabel12.style.marginBottom = "10px";
bylabel12.style.textAlign = "right";
let bylabel13 = document.getElementsByTagName("label").namedItem("l13");
bylabel13.style.width = "35%";
bylabel13.style.padding = "0.5rem 1.5rem";
bylabel13.style.boxSizing = "borderBox";
bylabel13.style.display = "inlineBlock";
bylabel13.style.marginBottom = "10px";
bylabel13.style.textAlign = "right";
let bylabel14 = document.getElementsByTagName("label").namedItem("l14");
bylabel14.style.width = "35%";
bylabel14.style.padding = "0.5rem 1.5rem";
bylabel14.style.boxSizing = "borderBox";
bylabel14.style.display = "inlineBlock";
bylabel14.style.marginBottom = "10px";
bylabel14.style.textAlign = "right";
let bylabel15 = document.getElementsByTagName("label").namedItem("l15");
bylabel15.style.width = "35%";
bylabel15.style.padding = "0.5rem 1.5rem";
bylabel15.style.boxSizing = "borderBox";
bylabel15.style.display = "inlineBlock";
bylabel15.style.marginBottom = "10px";
bylabel15.style.textAlign = "right";
let bylabel16 = document.getElementsByTagName("label").namedItem("l16");
bylabel16.style.width = "35%";
bylabel16.style.padding = "0.5rem 1.5rem";
bylabel16.style.boxSizing = "borderBox";
bylabel16.style.display = "inlineBlock";
bylabel16.style.marginBottom = "10px";
bylabel16.style.textAlign = "right";
// width: 20%;
// display: inline-block;
// border-radius: 4px;
// border: 1px solid #cccccc;
// padding: 0.5rem 1.5rem;
let byselect1 = document.getElementsByTagName("select").namedItem("b1");
byselect1.style.width = "100px";
byselect1.style.display = "inlineBlock";
byselect1.style.borderRadius = "4px";
byselect1.style.border = "1px solid #cccccc";
byselect1.style.padding = "0.5rem 1.5rem";
let byselect2 = document.getElementsByTagName("select").namedItem("b2");
byselect2.style.width = "20%";
byselect2.style.display = "inlineBlock";
byselect2.style.borderRadius = "4px";
byselect2.style.border = "1px solid #cccccc";
byselect2.style.padding = "0.5rem 1.5rem";
let byselect3 = document.getElementsByTagName("select").namedItem("b3");
byselect3.style.width = "20%";
byselect3.style.display = "inlineBlock";
byselect3.style.borderRadius = "4px";
byselect3.style.border = "1px solid #cccccc";
byselect3.style.padding = "0.5rem 1.5rem";
let byselect4 = document.getElementsByTagName("select").namedItem("b4");
byselect4.style.width = "20%";
byselect4.style.display = "inlineBlock";
byselect4.style.borderRadius = "4px";
byselect4.style.border = "1px solid #cccccc";
byselect4.style.padding = "0.5rem 1.5rem";
let byselect5 = document.getElementsByTagName("select").namedItem("b5");
byselect5.style.width = "20%";
byselect5.style.display = "inlineBlock";
byselect5.style.borderRadius = "4px";
byselect5.style.border = "1px solid #cccccc";
byselect5.style.padding = "0.5rem 1.5rem";
